### ISSUE TITLE
pages/posts containing a block used as an inner block, are not listed in the block catalog GUI

### ISSUE THREAD

**Issue by skorasaurus** [10up/block-catalog#5]
### Describe the bug

Oddly, when viewing the catalog page (e.g. wp-admin/edit.php?block-catalog=core-preformatted) that contain a particular block, when that block is used as an inner block, that page is not listed in the GUI.  

However, when using the `wp block-catalog find` command, posts containing blocks that are used as inner blocks are returned in the results. 

I am able to reproduce in both instances when the posts have published status or draft status. 

### Steps to Reproduce

1. create a new post or page, ideally on a fresh, plain site with minimal content. 
2. add a inner block to the post content.
In the code example below, there's a preformatted block within a group block; and it's the only use of the preformatted block on this site. 

```
<!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} -->

<div class="wp-block-group"><!-- wp:paragraph -->
<p>this is an example of within a group block</p>
<!-- /wp:paragraph -->

<!-- wp:preformatted -->
<pre class="wp-block-preformatted">this is preformatted text within a group block</pre>
<!-- /wp:preformatted --></div>
<!-- /wp:group -->
```
3. publish
4. Index posts
5. view block catalog (wp-admin/edit-tags.php?taxonomy=block-catalog). You'll see that the block, when used, as an inner block, is included in the count of how many times that block appears on the site. 
6. visit the catalog page for a particular block (wp-admin/edit.php?block-catalog=core-preformatted); you'll see that no pages or posts are listed as containing that block. 
7. wp block-catalog find core/preformatted ; you'll find that the post/page is correctly listed containing the preformatted block 

### Screenshots, screen recording, code snippet

![Selection_300](https://github.com/10up/block-catalog/assets/955351/7545b804-3fe3-459e-8674-74b37d188db4)
![Selection_301](https://github.com/10up/block-catalog/assets/955351/172c3e70-a9f2-4795-8537-87e217e4ad29)

### Environment information

n/a 

### WordPress information

gutenberg 15.8.1, WP 6.2.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dsawardekar** [comment]
@skorasaurus This is most likely due to the way WordPress Taxonomy screens filter by post type. When you are under a Post Type's Block Catalog page, you are effectively filtering for Block Catalog terms within a post type. When running under WP CLI mode, the query matches on any Post Type hence you see the matched results.

A possible workaround is to add the query parameter, `post_type=<foo>` to the URL with the empty results. That will force the query to search across that post type.

**Comment by sksaju** [comment]
Hi @skorasaurus, could you kindly confirm whether this issue still persists? I am unable to reproduce it on my end. Thank you

cc: @jeffpaul

**Comment by skorasaurus** [comment]
Yes, I can confirm this issue no longer exists in 1.5.3 

Thank you for your work on this.
