### ISSUE TITLE
Critical Flow Documentation - Block Catalog

### ISSUE THREAD

**Issue by ankitguptaindia** [10up/block-catalog#62]
### Objective: 

This GitHub issue will serve as a task to prepare Critical Flow (also known as Test Cases) for this repository/plugin.
- **[Guide for Creating Critical Flow of 10up OSS Projects](https://docs.google.com/document/d/1rNv_jHxsQT-AKSJ9QC2HGH-rRKAlTJOoGBtP10w_zV0/edit#heading=h.ucn4farfwxyf).**

**Please comment on this issue if you don't have:**

-  Access to edit Wiki Pages
-  The repository does not have Wiki Page enabled

**Comment by sudip-md** [comment]
Hi @ankitguptaindia I have added Critical flow documentation in wiki for block catalog plugin. It can be founded [here](https://github.com/10up/block-catalog/wiki/Testing-instructions-for-critical-flows)

**Comment by ankitguptaindia** [comment]
Thanks @sudip-md. It looks great and works well for quick testing. It would be great if we could add some cases to cover the following:

- WP CLI use with this plugin
- Navigating to any Block Editor post type will also show you the list of blocks present in a post. 
- Filtering the listing to only show posts that contain a specific block

**Comment by sudip-md** [comment]
Hi @ankitguptaindia I have updated below cases in wiki, Please review it and let me know if you need any changes. Thanks

- WP CLI use with this plugin
- Navigating to any Block Editor post type will also show you the list of blocks present in a post.
- Filtering the listing to only show posts that contain a specific block
