### ISSUE TITLE
PHP 8.2 deprecation for using ${var} in strings is deprecated

### ISSUE THREAD

**Issue by claytoncollie** [10up/block-catalog#7]
### Describe the bug

I am running my site on PHP 8.2 with `WP_DEBUG` set to `true`. The error logs at the top of the screen flag the use of variables in strings.

`Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /var/www/html/wp-content/plugins/block-catalog/includes/core.php on line 166`

`Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /var/www/html/wp-content/plugins/block-catalog/includes/core.php on line 184`

### Steps to Reproduce

1. Update to PHP 8.2
2. enabled WP_DEBUG
3. Activate this plugin
4. View the frontend

### WordPress information

WordPress 6.2.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by claytoncollie** [comment]
@dsawardekar Found this while using PHP 8.2. Let me know if you want a PR or can handle it yourself.

**Comment by dsawardekar** [comment]
Good catch, @claytoncollie ! I can take a look at this next week, but PRs are most welcome.

**Comment by dsawardekar** [comment]
This was fixed in https://github.com/10up/block-catalog/pull/9/files#diff-21e944aca0f42ff6529bde979b0fd787d00e010406e6642f947e71bf5e6f5ad1.

**Comment by kmgalanakis** [comment]
@dsawardekar I see the PR that fixes this is already merged and released. Should we move this issue to `Done`?

**Comment by dsawardekar** [comment]
Good catch @kmgalanakis, I forgot to close that with the fix. This is fixed in 1.5, closing.
