### ISSUE TITLE
Incorrect Get Started Instructions: change the `WP-Admin > Tools > Block` to `WP-Admin > Settings >Convert to Blocks`

### ISSUE THREAD

**Issue by kipmyk** [10up/block-catalog#71]
In [Getting Started](https://github.com/10up/block-catalog?tab=readme-ov-file#getting-started),

We'd need to update:

>On activation, the plugin will prompt you to index your content. You need to do this first before you will be able to see the various blocks used on your site. You can also go to WP-Admin > Tools > Block Catalog to do this yourself.

To 

>On activation, the plugin will prompt you to index your content. You need to do this first before you will be able to see the various blocks used on your site. You can also go to WP-Admin > Settings >Convert to Blocks Catalog to do this yourself.

This is because to access the Convert Blocks page, once needs to go `WP-Admin > Settings > Convert to Blocks`

**Comment by jeffpaul** [comment]
@kipmyk as this issue is in the Block Catalog repo (and not the Convert to Blocks repo) then I think the current description in the readme is accurate for getting to the Block Catalog settings.  Perhaps you're testing the Convert to Blocks plugin and came to the wrong repo?

**Comment by kipmyk** [comment]
Hey @jeffpaul, I downloaded it from [WordPress.org](https://wordpress.org/plugins/block-catalog/), and I saw this:

![Image](https://github.com/user-attachments/assets/49d0bf96-67e8-44ba-8d4a-1648c17b1b9d)
 
Perhaps we could also update it.
